# Generated by Django 4.0.3 on 2022-05-04 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_notificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='tipo',
            field=models.IntegerField(default=0),
        ),
    ]
