# Generated by Django 4.0.3 on 2022-05-04 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_notificacao_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='alertado',
            field=models.IntegerField(default=0),
        ),
    ]
