# Generated by Django 4.0.3 on 2022-05-04 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_notificacao_alertado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='vizualizado',
            field=models.IntegerField(default=0),
        ),
    ]
