# Generated by Django 4.0.3 on 2022-05-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_notificacao_id_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acerto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catAcertadas', models.IntegerField(default=0)),
                ('id_usuario', models.IntegerField(default=-1)),
                ('nome_usuario', models.CharField(max_length=100)),
                ('valorGanho', models.FloatField(default=0)),
                ('valorPerdido', models.FloatField(default=0)),
                ('valorTotalApostado', models.FloatField(default=0)),
            ],
        ),
    ]
