# Generated by Django 4.0.3 on 2022-04-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apostas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aposta',
            name='dataA',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aposta',
            name='valor',
            field=models.FloatField(default=0.0),
        ),
    ]
