# Generated by Django 4.0.2 on 2022-05-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apostas', '0002_aposta_dataa_aposta_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aposta',
            name='id_usuario',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aposta',
            name='pos1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aposta',
            name='pos10',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aposta',
            name='pos2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aposta',
            name='pos3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aposta',
            name='pos4',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aposta',
            name='pos5',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aposta',
            name='pos6',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aposta',
            name='pos7',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aposta',
            name='pos8',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aposta',
            name='pos9',
            field=models.IntegerField(default=0),
        ),
    ]
