# Generated by Django 4.0.3 on 2022-04-30 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0014_filme_lingua'),
        ('apostas', '0003_resultado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultado',
            name='id_indicado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='filmes.nomination'),
        ),
    ]
