# Generated by Django 4.0.3 on 2022-05-01 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apostas', '0004_alter_aposta_pos1_alter_aposta_pos10_and_more'),
        ('apostas', '0004_alter_resultado_id_indicado'),
    ]

    operations = [
    ]
