# Generated by Django 4.0.3 on 2022-04-11 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='ano',
            field=models.IntegerField(default=2021),
        ),
        migrations.AddField(
            model_name='filme',
            name='ava_imdb',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='filme',
            name='ava_letter',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='filme',
            name='ava_tmdb',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='filme',
            name='diretor',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='filme',
            name='poster',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='filme',
            name='sinopse',
            field=models.TextField(default=''),
        ),
    ]
