# Generated by Django 4.0.3 on 2022-04-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0002_filme_ano_filme_ava_imdb_filme_ava_letter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_filme', models.IntegerField()),
                ('banner', models.URLField(default='')),
            ],
        ),
    ]
