# Generated by Django 4.0.3 on 2022-04-11 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0003_banner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
