# Generated by Django 4.0.3 on 2022-04-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0005_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elenco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeAtor', models.CharField(max_length=100)),
                ('nomePersonagem', models.CharField(max_length=100)),
                ('id_filme', models.IntegerField()),
            ],
        ),
    ]
