# Generated by Django 4.0.3 on 2022-04-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0006_elenco'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='ondeAssistirImg',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='filme',
            name='ondeAssistirLink',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='filme',
            name='servico',
            field=models.CharField(default='', max_length=100),
        ),
    ]
