# Generated by Django 4.0.3 on 2022-04-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0007_filme_ondeassistirimg_filme_ondeassistirlink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='duracao',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='filme',
            name='genero',
            field=models.CharField(default='', max_length=100),
        ),
    ]
