# Generated by Django 4.0.3 on 2022-04-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0008_filme_duracao_filme_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100)),
                ('responsavel', models.CharField(max_length=100)),
                ('id_filme', models.IntegerField()),
            ],
        ),
    ]
