# Generated by Django 4.0.3 on 2022-04-12 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0009_nomination'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='ava_tomatoes',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='filme',
            name='link_imdb',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='filme',
            name='link_letter',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='filme',
            name='link_tmdb',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='filme',
            name='link_tomatoes',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='filme',
            name='tomatoe',
            field=models.IntegerField(default=0),
        ),
    ]
