# Generated by Django 4.0.3 on 2022-04-12 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0010_filme_ava_tomatoes_filme_link_imdb_filme_link_letter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filme',
            old_name='tomatoe',
            new_name='tomatoes',
        ),
    ]
