# Generated by Django 4.0.3 on 2022-04-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0012_remove_filme_ava_tomatoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='elenco',
            name='imagem',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='elenco',
            name='link_tmdb',
            field=models.URLField(default=''),
        ),
    ]
