# Generated by Django 4.0.3 on 2022-04-29 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0013_elenco_imagem_elenco_link_tmdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='lingua',
            field=models.CharField(default='Inglês', max_length=100),
        ),
    ]
