# Generated by Django 4.0.3 on 2022-05-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0014_filme_lingua'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='edicao',
            field=models.IntegerField(default=2022),
        ),
    ]
